[package]
name = "learn_tuple"
version = "0.1.0"
authors = ["Alien Xu <734329218@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
